name: Run tests

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: install dependencies
      run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install automake libtool libusb-1.0-0-dev libjack-jackd2-dev libsamplerate0-dev libsndfile1-dev autopoint gettext libjson-glib-dev libgtk-4-dev libsystemd-dev
          sudo apt-get -y --no-install-recommends install libcunit1-dev
    - name: install SDM
      run: curl -L https://raw.githubusercontent.com/gitbls/sdm/master/EZsdmInstaller | bash
    - name: build images
      working-directory: ./scripts/image
      run: bash create-image-with-backports.sh
    - name: get hash
      id: get_sha
      run: echo "sha=$(git rev-parse --short HEAD)"  >> "$GITHUB_OUTPUT"
    - name: create tag
      id: create_tag
      run: |
        git tag $(git rev-parse --short HEAD) -f
        git push origin $(git rev-parse --short HEAD) -f
    - name: Gzip file
      run: tar cvf - "./scripts/image/pushpin-groovebox-$(git rev-parse --short HEAD).img" | gzip -9 - > "pushpin-groovebox-$(git rev-parse --short HEAD).img.tar.gz"
    - name: create release
      uses: softprops/action-gh-release@v2
      with:
        files: ./*.img.tar.gz
        tag_name: "${{ steps.get_sha.outputs.sha }}"